# Generated by Django 3.1.2 on 2020-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
