# Generated by Django 3.1.2 on 2020-11-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.CharField(default='???', max_length=30),
        ),
    ]
